server:
  port: 8899
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #Git 仓库位置
          uri: https://github.com/SSpring1014
          #Git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: config-repo,config-server
          #访问Git仓库的用户名
          username: 603724787@qq.com
          #访问Git仓库的密码
          password: xia1014 